# Generated by Django 2.1.5 on 2019-01-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created_in_year',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
