# Generated by Django 2.1.5 on 2019-01-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_created_in_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Acknowledge-Message'), (2, 'Yes-No-Message')], default=1),
            preserve_default=False,
        ),
    ]
