# Generated by Django 2.1.5 on 2019-01-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
