# Generated by Django 2.1.5 on 2019-01-19 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_savegame_playing_as'),
        ('messaging', '0004_message_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='savegame',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='account.Savegame'),
            preserve_default=False,
        ),
    ]
