# Generated by Django 2.1.7 on 2019-02-16 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0023_auto_20190119_1753'),
        ('military', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regiment',
            name='county',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='regiments', to='location.County'),
            preserve_default=False,
        ),
    ]
