# Generated by Django 2.1.7 on 2019-02-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('military', '0002_regiment_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='regimenttype',
            name='is_long_range',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regimenttype',
            name='long_range_tile_distance',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
