# Generated by Django 2.1.7 on 2019-02-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('military', '0003_auto_20190216_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='regimenttype',
            name='default_type',
            field=models.BooleanField(default=False),
        ),
    ]
