# Generated by Django 2.1.7 on 2019-02-17 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_savegame_playing_as'),
        ('military', '0005_auto_20190216_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlefieldtile',
            name='savegame',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='battlefield_tiles', to='account.Savegame'),
            preserve_default=False,
        ),
    ]
