# Generated by Django 2.1.7 on 2019-02-17 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('military', '0006_battlefieldtile_savegame'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlefieldtile',
            name='regiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='on_battlefield_tile', to='military.Regiment'),
        ),
    ]
