# Generated by Django 2.1.7 on 2019-02-17 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_savegame_playing_as'),
        ('military', '0007_battlefieldtile_regiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='savegame',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='account.Savegame'),
            preserve_default=False,
        ),
    ]
