# Generated by Django 2.1.7 on 2019-02-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('military', '0008_battle_savegame'),
    ]

    operations = [
        migrations.AddField(
            model_name='regimenttype',
            name='icon_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
