# Generated by Django 2.1.7 on 2019-02-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('military', '0009_regimenttype_icon_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regimenttype',
            old_name='icon_name',
            new_name='icon_path',
        ),
        migrations.AlterField(
            model_name='regiment',
            name='upgrades',
            field=models.ManyToManyField(blank=True, related_name='regiments', to='military.RegimentUpgrade'),
        ),
    ]
