# Generated by Django 2.1.7 on 2019-02-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('military', '0011_auto_20190224_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='regiment',
            name='last_move_in_round',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
