# Generated by Django 2.1.7 on 2019-02-24 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('military', '0012_regiment_last_move_in_round'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regiment',
            old_name='last_move_in_round',
            new_name='last_action_in_round',
        ),
    ]
