# Generated by Django 2.1.7 on 2019-03-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('military', '0013_auto_20190224_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regimenttype',
            name='long_range_tile_distance',
        ),
        migrations.AddField(
            model_name='regimenttype',
            name='long_range_pattern',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Crossbow'), (2, 'Bow')], null=True),
        ),
    ]
