# Generated by Django 2.1.7 on 2019-03-02 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('military', '0014_auto_20190302_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regimenttype',
            name='long_range_pattern',
        ),
    ]
