# Generated by Django 2.1.7 on 2019-03-02 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('military', '0015_remove_regimenttype_long_range_pattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='military.Battle')),
            ],
        ),
        migrations.AddField(
            model_name='regiment',
            name='current_morale',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
