# Generated by Django 2.1.7 on 2019-03-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('military', '0016_auto_20190302_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='battlelogentry',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='regiment',
            name='current_morale',
            field=models.SmallIntegerField(default=0),
        ),
    ]
