# Generated by Django 2.1.7 on 2019-03-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('military', '0017_auto_20190302_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlelogentry',
            name='text',
            field=models.TextField(),
        ),
    ]
