# Generated by Django 2.1.7 on 2019-03-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('military', '0018_auto_20190302_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='attacker_regiments',
            field=models.ManyToManyField(related_name='attacker_in_battles', to='military.Regiment'),
        ),
        migrations.AddField(
            model_name='battle',
            name='defender_regiments',
            field=models.ManyToManyField(related_name='defender_in_battles', to='military.Regiment'),
        ),
    ]
