# Generated by Django 2.2.9 on 2019-12-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('military', '0019_auto_20190303_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlefieldtile',
            name='distance_weight',
            field=models.FloatField(default=0, help_text='Weighted distance on attacker side', verbose_name='Distance weight'),
        ),
    ]
