# Generated by Django 2.2.9 on 2019-12-23 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('military', '0020_battlefieldtile_distance_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battlefieldtile',
            old_name='distance_weight',
            new_name='base_distance_weight',
        ),
    ]
