# Generated by Django 2.2.9 on 2019-12-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('military', '0021_auto_20191223_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battlefieldtile',
            old_name='base_distance_weight',
            new_name='distance_weight_attacker',
        ),
        migrations.AddField(
            model_name='battlefieldtile',
            name='distance_weight_defender',
            field=models.FloatField(default=0, help_text='Weighted distance on defender side', verbose_name='Distance weight'),
        ),
    ]
