# Generated by Django 2.1.3 on 2019-01-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savegame',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
