# Generated by Django 2.1.3 on 2019-01-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190101_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='savegame',
            name='current_year',
            field=models.PositiveIntegerField(default=800),
        ),
    ]
