# Generated by Django 2.1.3 on 2019-01-06 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynasty', '0011_auto_20190106_1857'),
        ('account', '0003_savegame_current_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='savegame',
            name='playing_as',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playing_in_savegame', to='dynasty.Dynasty'),
        ),
    ]
