# Generated by Django 2.1.3 on 2018-12-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0002_auto_20181118_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationnamepostfix',
            name='text',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='locationnameprefix',
            name='text',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
