# Generated by Django 2.1.3 on 2019-01-06 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0003_auto_20181223_2038'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personname',
            unique_together={('name', 'gender')},
        ),
    ]
