# Generated by Django 2.1.3 on 2018-12-23 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MapDot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_border', models.BooleanField(default=False)),
                ('is_capital', models.BooleanField(default=False)),
                ('coordinate_x', models.IntegerField()),
                ('coordinate_y', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='county',
            name='primary_color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mapdot',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map_dots', to='location.County'),
        ),
        migrations.AddField(
            model_name='mapdot',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_dots', to='location.Map'),
        ),
    ]
