# Generated by Django 2.1.3 on 2018-12-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20181223_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapdot',
            name='is_wasteland',
            field=models.BooleanField(default=False),
        ),
    ]
