# Generated by Django 2.1.3 on 2018-12-23 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_mapdot_is_wasteland'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapdot',
            old_name='country',
            new_name='county',
        ),
    ]
