# Generated by Django 2.1.3 on 2018-12-24 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_map_political_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapdot',
            name='is_wasteland',
        ),
    ]
