# Generated by Django 2.1.3 on 2018-12-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_remove_mapdot_is_wasteland'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={'verbose_name_plural': 'Counties'},
        ),
        migrations.AddField(
            model_name='county',
            name='target_size',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mapdot',
            name='terrain',
            field=models.PositiveIntegerField(choices=[(1, 'Water'), (2, 'Land')], default=1),
        ),
    ]
