# Generated by Django 2.1.3 on 2018-12-29 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_auto_20181229_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='county',
            name='area_type',
        ),
    ]
