# Generated by Django 2.1.3 on 2018-12-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_remove_county_area_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='target_size',
            field=models.FloatField(default=0),
        ),
    ]
