# Generated by Django 2.1.3 on 2018-12-29 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_auto_20181229_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='target_size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
