# Generated by Django 2.1.3 on 2018-12-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0012_auto_20181230_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapdot',
            name='coordinate_x',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='mapdot',
            name='coordinate_y',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='mapdot',
            name='terrain',
            field=models.PositiveIntegerField(choices=[(1, 'Water'), (2, 'Land')], db_index=True, default=1),
        ),
    ]
