# Generated by Django 2.1.3 on 2019-01-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0013_auto_20181230_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='dimension',
            field=models.PositiveIntegerField(default=0, help_text='Height/Width of the map'),
        ),
    ]
