# Generated by Django 2.1.3 on 2019-01-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0014_map_dimension'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapdot',
            name='is_water',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='mapdot',
            name='terrain',
            field=models.PositiveIntegerField(choices=[(1, 'Fields'), (2, 'Plains'), (3, 'Swamp'), (4, 'Steppe'), (5, 'Woods'), (6, 'Hills'), (7, 'Mountains')], db_index=True, default=1),
        ),
    ]
