# Generated by Django 2.1.3 on 2019-01-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0015_auto_20190101_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapdot',
            name='terrain',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Fields'), (2, 'Plains'), (3, 'Swamp'), (4, 'Steppe'), (5, 'Woods'), (6, 'Hills'), (7, 'Mountains')], db_index=True, null=True),
        ),
    ]
