# Generated by Django 2.1.3 on 2019-01-01 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190101_1903'),
        ('location', '0017_map_savegame'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='savegame',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='counties', to='account.Savegame'),
            preserve_default=False,
        ),
    ]
