# Generated by Django 2.1.5 on 2019-01-13 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynasty', '0013_remove_dynasty_ruling_over'),
        ('location', '0021_auto_20190101_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='ruled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ruling_over', to='dynasty.Dynasty'),
        ),
    ]
