# Generated by Django 2.1.5 on 2019-01-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0022_county_ruled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='gold',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='county',
            name='manpower',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='mapdot',
            name='gold',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mapdot',
            name='manpower',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
