# Generated by Django 3.2.8 on 2021-10-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0023_auto_20190119_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapdot',
            name='level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
