# Generated by Django 3.0.6 on 2020-08-01 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0004_savegame_playing_as'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastleUpgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Castle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('savegame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='castles', to='account.Savegame')),
                ('upgrades', models.ManyToManyField(blank=True, to='castle.CastleUpgrade')),
            ],
        ),
    ]
