# Generated by Django 3.0.6 on 2020-08-01 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0023_auto_20190119_1753'),
        ('castle', '0002_castle_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castle',
            name='county',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='castle', to='location.County'),
        ),
    ]
