# Generated by Django 3.0.6 on 2020-08-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castle', '0003_auto_20200801_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='castleupgrade',
            name='costs',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='castleupgrade',
            name='defense_bonus',
            field=models.SmallIntegerField(default=0),
        ),
    ]
