GENDER_MALE = 1
GENDER_FEMALE = 2
GENDER_CHOICES = (
    (GENDER_MALE, 'male'),
    (GENDER_FEMALE, 'female')
)

MAX_SKILL_POINTS = 100

# Marriage
MIN_NUBILE_AGE_WOMEN = 14
MAX_NUBILE_AGE_WOMEN = 32

MIN_NUBILE_AGE_MEN = 16
