# Generated by Django 2.1.3 on 2018-11-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nobility', models.BooleanField(default=True)),
                ('from_location', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, 'male'), (2, 'female')])),
                ('birth_year', models.PositiveIntegerField()),
            ],
        ),
    ]
