# Generated by Django 2.1.3 on 2019-01-05 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynasty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dynasty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Alcoholic'), (2, 'Cruel'), (3, 'Sodomist'), (4, 'Tiny'), (5, 'Giant'), (6, 'Strategist')])),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='charisma',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='person',
            name='fama',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='father',
            field=models.ManyToManyField(related_name='fathers_children', to='dynasty.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='intelligence',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='person',
            name='leadership',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='person',
            name='mother',
            field=models.ManyToManyField(related_name='mothers_children', to='dynasty.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='from_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='natives', to='location.County'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='traits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynasty.Trait'),
        ),
    ]
