# Generated by Django 2.1.3 on 2019-01-05 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190101_1903'),
        ('dynasty', '0002_auto_20190105_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='savegame',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='account.Savegame'),
            preserve_default=False,
        ),
    ]
