# Generated by Django 2.1.3 on 2019-01-05 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynasty', '0003_person_savegame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='savegame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='account.Savegame'),
        ),
    ]
