# Generated by Django 2.1.3 on 2019-01-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynasty', '0004_auto_20190105_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='traits',
        ),
        migrations.AddField(
            model_name='person',
            name='traits',
            field=models.ManyToManyField(to='dynasty.Trait'),
        ),
    ]
