# Generated by Django 2.1.3 on 2019-01-06 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynasty', '0005_auto_20190105_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='father',
        ),
        migrations.AddField(
            model_name='person',
            name='father',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fathers_children', to='dynasty.Person'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='person',
            name='mother',
        ),
        migrations.AddField(
            model_name='person',
            name='mother',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mothers_children', to='dynasty.Person'),
            preserve_default=False,
        ),
    ]
