# Generated by Django 2.1.3 on 2019-01-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynasty', '0007_auto_20190106_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='trait',
            name='incompatible_traits',
            field=models.ManyToManyField(related_name='_trait_incompatible_traits_+', to='dynasty.Trait'),
        ),
        migrations.AlterField(
            model_name='trait',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Alcoholic'), (2, 'Cruel'), (3, 'Sodomist'), (4, 'Tiny'), (5, 'Giant'), (6, 'Strategist'), (7, 'Religious Zeal')]),
        ),
    ]
