# Generated by Django 2.1.3 on 2019-01-06 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0021_auto_20190101_2003'),
        ('dynasty', '0009_auto_20190106_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='from_location',
        ),
        migrations.AddField(
            model_name='dynasty',
            name='current_dynast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules_over', to='dynasty.Person'),
        ),
        migrations.AddField(
            model_name='dynasty',
            name='from_location',
            field=models.CharField(default='asdf', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dynasty',
            name='ruling_over',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='natives', to='location.County'),
        ),
        migrations.AddField(
            model_name='person',
            name='death_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='dynasty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='dynasty.Dynasty'),
        ),
    ]
