# Generated by Django 2.1.3 on 2019-01-06 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynasty', '0010_auto_20190106_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynasty',
            name='savegame',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='dynasties', to='account.Savegame'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='dynasty',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='dynasty.Dynasty'),
            preserve_default=False,
        ),
    ]
