# Generated by Django 2.1.5 on 2019-01-13 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0022_county_ruled_by'),
        ('dynasty', '0013_remove_dynasty_ruling_over'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynasty',
            name='home_county',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='native_dynasty', to='location.County'),
        ),
    ]
