# Generated by Django 2.1.5 on 2019-01-20 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynasty', '0014_dynasty_home_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='spouse',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='married_to', to='dynasty.Person'),
        ),
    ]
